/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.glb 
Author: Poll_Creations (https://sketchfab.com/PollStudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-cute-robot-cbb370b40af149dd856bac5f0374af60
Title: Little cute robot
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Models/robot.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  
  // Play all animations in infinite loop
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        if (action) {
          action.reset().play();
          action.setLoop(2201); // LoopRepeat = 2201 (infinite loop)
        }
      });
    }
  }, [actions]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.147}>
          <group name="Root">
            <group name="Armature001">
              <primitive object={nodes.Armature001_rootJoint} />
              <group name="Sphere" />
              <skinnedMesh name="Sphere_0" geometry={nodes.Sphere_0.geometry} material={materials.plastic} skeleton={nodes.Sphere_0.skeleton} />
              <skinnedMesh name="Sphere_1" geometry={nodes.Sphere_1.geometry} material={materials['Material.001']} skeleton={nodes.Sphere_1.skeleton} />
              <skinnedMesh name="Sphere_2" geometry={nodes.Sphere_2.geometry} material={materials['Material.002']} skeleton={nodes.Sphere_2.skeleton} />
              <skinnedMesh name="Sphere_3" geometry={nodes.Sphere_3.geometry} material={materials['Material.004']} skeleton={nodes.Sphere_3.skeleton} />
            </group>
            <group name="Sun001" position={[-6.075, 9.115, 9.271]} rotation={[-0.782, -0.182, -0.132]}>
              <group name="Sun001_1" />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/robot.glb')